@export on;
@export set filename="D:\conversores\TRON\Tron\dados\ferias.txt";
@export set BinaryFormat="Don't Export";
@export set CsvColumnDelimiter="|";
@export set CsvRemoveNewlines="true";
@export set CsvRowDelimiter="\r\n";
@export set Encoding="Cp1252";
SELECT TBLITEPRGFRS.CODEMPFOL, TBLITEPRGFRS.MATEPGCTT, TBLITEPRGFRS.DTAINIAQUPRGFRS,
       TBLITEPRGFRS.DTAFINAQUITEPRGFRS, TBLITEPRGFRS.DTAINIGOZPRGFRS, TBLITEPRGFRS.DTAFINGOZPRGFRS,
       TBLITEPRGFRS.DTAINIABOPRGFRS, TBLITEPRGFRS.DTAFINABOPRGFRS
  FROM TBLITEPRGFRS
ORDER BY TBLITEPRGFRS.CODEMPFOL, TBLITEPRGFRS.MATEPGCTT, TBLITEPRGFRS.DTAINIAQUPRGFRS;
@export off;
