SELECT TBLITEPRGFRS.CODEMPFOL, TBLITEPRGFRS.MATEPGCTT, TBLITEPRGFRS.DTAINIAQUPRGFRS,
       TBLITEPRGFRS.DTAFINAQUITEPRGFRS, TBLITEPRGFRS.DTAINIGOZPRGFRS, TBLITEPRGFRS.DTAFINGOZPRGFRS,
       TBLITEPRGFRS.DTAINIABOPRGFRS, TBLITEPRGFRS.DTAFINABOPRGFRS
  FROM TBLITEPRGFRS
 --WHERE tbliteprgfrs.codempfol IN (8)
ORDER BY TBLITEPRGFRS.CODEMPFOL, TBLITEPRGFRS.MATEPGCTT, TBLITEPRGFRS.DTAINIAQUPRGFRS
