SELECT TBLEMP.*, TBLEMPDET.*, TBLEMPFOL.*
  FROM TBLEMP, TBLEMPDET, TBLEMPFOL
 WHERE TBLEMP.CODEMP = TBLEMPDET.CODEMP
   AND TBLEMP.CODEMP = TBLEMPFOL.CODEMPFOL
   --AND tblemp.codemp IN (4587)
   --AND TBLEMP.RAZSOCEMP LIKE '%energ%'
   --AND TBLEMP.INSEMP IN ( '01.724.294/0001-67', '23.119.568/0001-21' )
ORDER BY TBLEMP.CODEMP